import type { VoiceParamInput, VoiceProfile } from '../../core/db/types'

const VOICES: VoiceProfile[] = [
  // 中文普通话 - 青年男声
  {
    id: 'male-qn-qingse',
    displayName: '青涩青年',
    description: '青涩青年音色，适合日常对话内容。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  {
    id: 'male-qn-jingying',
    displayName: '精英青年',
    description: '精英青年音色，自信干练。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  {
    id: 'male-qn-badao',
    displayName: '霸道青年',
    description: '霸道青年音色，气场强大。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  {
    id: 'male-qn-daxuesheng',
    displayName: '青年大学生',
    description: '大学生音色，青春活力。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  // 中文普通话 - 女声
  {
    id: 'female-shaonv',
    displayName: '少女',
    description: '少女音色，甜美可爱。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  {
    id: 'female-yujie',
    displayName: '御姐',
    description: '御姐音色，成熟妩媚。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  {
    id: 'female-chengshu',
    displayName: '成熟女性',
    description: '成熟女性音色，优雅知性。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  {
    id: 'female-tianmei',
    displayName: '甜美女性',
    description: '甜美女性音色，温柔亲切。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  // 中文普通话 - 特色音色
  {
    id: 'clever_boy',
    displayName: '聪明男童',
    description: '聪明男童音色，活泼机灵。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  {
    id: 'cute_boy',
    displayName: '可爱男童',
    description: '可爱男童音色，天真烂漫。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  {
    id: 'lovely_girl',
    displayName: '萌萌女童',
    description: '萌萌女童音色，软萌可爱。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  {
    id: 'cartoon_pig',
    displayName: '卡通猪小琪',
    description: '卡通猪小琪音色，搞怪有趣。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  {
    id: 'bingjiao_didi',
    displayName: '病娇弟弟',
    description: '病娇弟弟音色，二次元风格。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  {
    id: 'junlang_nanyou',
    displayName: '俊朗男友',
    description: '俊朗男友音色，温暖贴心。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  {
    id: 'chunzhen_xuedi',
    displayName: '纯真学弟',
    description: '纯真学弟音色，阳光少年。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  {
    id: 'lengdan_xiongzhang',
    displayName: '冷淡学长',
    description: '冷淡学长音色，高冷内敛。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  {
    id: 'badao_shaoye',
    displayName: '霸道少爷',
    description: '霸道少爷音色，强势自信。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  {
    id: 'tianxin_xiaoling',
    displayName: '甜心小玲',
    description: '甜心小玲音色，活泼甜美。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  {
    id: 'qiaopi_mengmei',
    displayName: '俏皮萌妹',
    description: '俏皮萌妹音色，古灵精怪。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  {
    id: 'wumei_yujie',
    displayName: '妩媚御姐',
    description: '妩媚御姐音色，成熟迷人。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  {
    id: 'diadia_xuemei',
    displayName: '嗲嗲学妹',
    description: '嗲嗲学妹音色，撒娇可爱。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  {
    id: 'danya_xuejie',
    displayName: '淡雅学姐',
    description: '淡雅学姐音色，知性优雅。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  // 中文普通话 - 专业风格
  {
    id: 'Chinese (Mandarin)_Reliable_Executive',
    displayName: '沉稳高管',
    description: '沉稳高管音色，专业可信。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  {
    id: 'Chinese (Mandarin)_News_Anchor',
    displayName: '新闻女声',
    description: '新闻女声，播报风格。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  {
    id: 'Chinese (Mandarin)_Mature_Woman',
    displayName: '傲娇御姐',
    description: '傲娇御姐音色，独特个性。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  {
    id: 'Chinese (Mandarin)_Unrestrained_Young_Man',
    displayName: '不羁青年',
    description: '不羁青年音色，洒脱随性。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  {
    id: 'Chinese (Mandarin)_Gentleman',
    displayName: '温润男声',
    description: '温润男声，儒雅温和。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  {
    id: 'Chinese (Mandarin)_Warm_Bestie',
    displayName: '温暖闺蜜',
    description: '温暖闺蜜音色，亲切知心。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  {
    id: 'Chinese (Mandarin)_Male_Announcer',
    displayName: '播报男声',
    description: '播报男声，专业播音风格。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  {
    id: 'Chinese (Mandarin)_Sweet_Lady',
    displayName: '甜美女声',
    description: '甜美女声，温柔动听。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  {
    id: 'Chinese (Mandarin)_Southern_Young_Man',
    displayName: '南方小哥',
    description: '南方小哥音色，温和亲切。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  {
    id: 'Chinese (Mandarin)_Wise_Women',
    displayName: '阅历姐姐',
    description: '阅历姐姐音色，成熟有智慧。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  {
    id: 'Chinese (Mandarin)_Radio_Host',
    displayName: '电台男主播',
    description: '电台男主播音色，磁性魅力。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  // 中文粤语
  {
    id: 'Cantonese_ProfessionalHost（F)',
    displayName: '粤语女主持',
    description: '粤语专业女主持，地道港味。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  {
    id: 'Cantonese_GentleLady',
    displayName: '粤语温柔女声',
    description: '粤语温柔女声，柔情似水。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  {
    id: 'Cantonese_ProfessionalHost（M)',
    displayName: '粤语男主持',
    description: '粤语专业男主持，沉稳大气。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  {
    id: 'Cantonese_CuteGirl',
    displayName: '粤语可爱女孩',
    description: '粤语可爱女孩，俏皮活泼。',
    language: 'zh',
    speedRange: [0.5, 2],
    pitchRange: [-10, 10],
    volumeRange: [0, 10],
  },
  // English
  {
    id: 'English_Trustworthy_Man',
    displayName: 'Trustworthy Man',
    description: 'English trustworthy male voice.',
    language: 'en',
    speedRange: [0.6, 1.8],
    pitchRange: [-8, 8],
    volumeRange: [0, 10],
  },
  {
    id: 'English_Graceful_Lady',
    displayName: 'Graceful Lady',
    description: 'English graceful female voice.',
    language: 'en',
    speedRange: [0.6, 1.8],
    pitchRange: [-8, 8],
    volumeRange: [0, 10],
  },
  {
    id: 'English_Aussie_Bloke',
    displayName: 'Aussie Bloke',
    description: 'English Australian accent.',
    language: 'en',
    speedRange: [0.6, 1.8],
    pitchRange: [-8, 8],
    volumeRange: [0, 10],
  },
  {
    id: 'English_Diligent_Man',
    displayName: 'Diligent Man',
    description: 'English diligent male voice.',
    language: 'en',
    speedRange: [0.6, 1.8],
    pitchRange: [-8, 8],
    volumeRange: [0, 10],
  },
  {
    id: 'English_Gentle-voiced_man',
    displayName: 'Gentle-voiced Man',
    description: 'English gentle male voice.',
    language: 'en',
    speedRange: [0.6, 1.8],
    pitchRange: [-8, 8],
    volumeRange: [0, 10],
  },
  // Japanese
  {
    id: 'Japanese_IntellectualSenior',
    displayName: '知性先輩',
    description: '日本語の知的な先輩の声。',
    language: 'ja',
    speedRange: [0.6, 1.8],
    pitchRange: [-8, 8],
    volumeRange: [0, 10],
  },
  {
    id: 'Japanese_DecisivePrincess',
    displayName: '決断の姫',
    description: '日本語の毅然とした姫の声。',
    language: 'ja',
    speedRange: [0.6, 1.8],
    pitchRange: [-8, 8],
    volumeRange: [0, 10],
  },
  {
    id: 'Japanese_LoyalKnight',
    displayName: '忠誠の騎士',
    description: '日本語の忠誠な騎士の声。',
    language: 'ja',
    speedRange: [0.6, 1.8],
    pitchRange: [-8, 8],
    volumeRange: [0, 10],
  },
  {
    id: 'Japanese_DominantMan',
    displayName: '支配的な男性',
    description: '日本語の支配的な男性の声。',
    language: 'ja',
    speedRange: [0.6, 1.8],
    pitchRange: [-8, 8],
    volumeRange: [0, 10],
  },
  {
    id: 'Japanese_ColdQueen',
    displayName: '冷たい女王',
    description: '日本語の冷徹な女王の声。',
    language: 'ja',
    speedRange: [0.6, 1.8],
    pitchRange: [-8, 8],
    volumeRange: [0, 10],
  },
  // Korean
  {
    id: 'Korean_SweetGirl',
    displayName: '달콤한 소녀',
    description: '한국어 달콤한 소녀 목소리.',
    language: 'multi',
    speedRange: [0.6, 1.8],
    pitchRange: [-8, 8],
    volumeRange: [0, 10],
  },
  {
    id: 'Korean_CheerfulBoyfriend',
    displayName: '유쾌한 남자친구',
    description: '한국어 유쾌한 남자친구 목소리.',
    language: 'multi',
    speedRange: [0.6, 1.8],
    pitchRange: [-8, 8],
    volumeRange: [0, 10],
  },
  {
    id: 'Korean_ElegantPrincess',
    displayName: '우아한 공주',
    description: '한국어 우아한 공주 목소리.',
    language: 'multi',
    speedRange: [0.6, 1.8],
    pitchRange: [-8, 8],
    volumeRange: [0, 10],
  },
  {
    id: 'Korean_BraveFemaleWarrior',
    displayName: '용감한 여전사',
    description: '한국어 용감한 여전사 목소리.',
    language: 'multi',
    speedRange: [0.6, 1.8],
    pitchRange: [-8, 8],
    volumeRange: [0, 10],
  },
]

export function listVoiceProfiles(): VoiceProfile[] {
  return VOICES
}

export function validateVoiceParams(input: VoiceParamInput): { valid: boolean; errors: string[] } {
  const errors: string[] = []

  const voiceId = input.voiceId ?? null
  const selectedVoice = voiceId ? VOICES.find((voice) => voice.id === voiceId) : null
  if (voiceId && !selectedVoice) {
    errors.push(`Unknown voiceId: ${voiceId}`)
  }

  const speed = input.speed ?? 1
  const pitch = input.pitch ?? 0
  const volume = input.volume ?? 1

  const speedRange: [number, number] = selectedVoice?.speedRange ?? [0.5, 2]
  const pitchRange: [number, number] = selectedVoice?.pitchRange ?? [-10, 10]
  const volumeRange: [number, number] = selectedVoice?.volumeRange ?? [0, 10]

  if (speed < speedRange[0] || speed > speedRange[1]) {
    errors.push(`speed out of range: ${speedRange[0]}-${speedRange[1]}`)
  }
  if (pitch < pitchRange[0] || pitch > pitchRange[1]) {
    errors.push(`pitch out of range: ${pitchRange[0]}-${pitchRange[1]}`)
  }
  if (volume < volumeRange[0] || volume > volumeRange[1]) {
    errors.push(`volume out of range: ${volumeRange[0]}-${volumeRange[1]}`)
  }

  return {
    valid: errors.length === 0,
    errors,
  }
}
